### ISSUE TITLE
Wrong number or type of arguments for overloaded function 'simpleCMLFactory'

### ISSUE THREAD

**Issue by vessenes** [skieffer/hola#2]
I'm back at this today.

I have your most recent fork of adaptagrams downloaded. 

`````` bash
$ python hola_v40e42.py
======================================================================
HOLA Layout for random/v40e42
Traceback (most recent call last):
  File "hola_v40e42.py", line 18, in <module>
    main()
  File "hola_v40e42.py", line 15, in main
    basic_tools.doHOLA(name, config=config)
  File "/home/user/src/hola/test/basic_tools.py", line 28, in doHOLA
    hola.hola(G, config=config, logger=logger, projLogger=projLogger)
  File "/home/user/src/hola/test/../hola/hola.py", line 502, in hola
    useNeighbourStress=True, useScaling=config.USE_SCALING_IN_MAJORIZATION)
  File "/home/user/src/hola/test/../hola/graphs.py", line 781, in shakeWithSolidEdges
    useScaling=useScaling)
  File "/home/user/src/hola/test/../hola/graphs.py", line 691, in setupMajLayout
    alg = adg.simpleCMLFactory(rs, es, iel, useNeighbourStress)
NotImplementedError: Wrong number or type of arguments for overloaded function 'simpleCMLFactory'.
  Possible C/C++ prototypes are:
    cola::simpleCMLFactory(vpsc::Rectangles &,std::vector< cola::Edge,std::allocator< cola::Edge > > const &,cola::RootCluster *,double const,bool)
    cola::simpleCMLFactory(vpsc::Rectangles &,std::vector< cola::Edge,std::allocator< cola::Edge > > const &,cola::RootCluster *,double const)```
``````

**Comment by skieffer** [comment]
Sorry, Peter. Too many separate projects, not evolving in tandem like they should, you know how it can go.

It should be working now. Also I’ve added test/test_menu.py to interactively launch tests on many different input graphs.
