### ISSUE TITLE
run test program error

### ISSUE THREAD

**Issue by time-river** [skieffer/hola#8]
Hello, I build the program according to your README, then run the test `test/test_menu.py`. However, it doesn't run. Error information:
```
ubuntu@VM-44-93-ubuntu:~/hola/hola/test$ ./test_menu.py
Output intermediate stage graphs? (y/n) y

orthowontist                                               random
    ( 0) h01                                                   (21) rand3a
    ( 1) h02                                                   (22) rand3b
    ( 2) h03                                                   (23) v100e99
    ( 3) h04                                                   (24) v100e99_pruned
    ( 4) h05                                                   (25) v120e126
    ( 5) h06                                                   (26) v120e128
    ( 6) h07                                                   (27) v120e140
    ( 7) h08                                                   (28) v200e210
                                                               (29) v200e220
sbgn                                                           (30) v40e41
    ( 8) Alanine-Valine-Leucine-biosynthesis_part_NC           (31) v40e42
    ( 9) Arginine-biosynthesis_NC                              (32) v40e43
    (10) Calvin_Cycle_NC                                       (33) v40e44
    (11) Glycolysis-Gluconeogenesis_NC                         (34) v40e45
    (12) Glycolysis-Gluconeogenesis_NC_min30x30                (35) v40e46
    (13) Glycolysis-Gluconeogenesis_NC_random2                 (36) v40e47
    (14) Glycolysis-Gluconeogenesis_NC_random3                 (37) v40e48
    (15) Glycolysis-Gluconeogenesis_NC_random                  (38) v50e100
    (16) Glycolysis-Gluconeogenesis_NC_random_min30x30         (39) v50e49
                                                               (40) v50e49_pruned
metro                                                          (41) v50e55
    (17) london                                                (42) v60e65
    (18) melb                                                  (43) v60e65_min30x30
    (19) sydney                                                (44) v60e66
    (20) wien-kurz                                             (45) v60e80
                                                               (46) v90e110

                                                           special
                                                               (47) core_with_trees
                                                               (48) lone_node
                                                               (49) straight_6
                                                               (50) X_4
                                                               (51) Y_4

Graph number, or q to quit> 17
======================================================================
HOLA Layout for metro/london
Traceback (most recent call last):
  File "./test_menu.py", line 83, in <module>
    main()
  File "./test_menu.py", line 79, in main
    basic_tools.doHOLA(name, config=config)
  File "/home/ubuntu/hola/hola/test/basic_tools.py", line 28, in doHOLA
    hola.hola(G, config=config, logger=logger, projLogger=projLogger)
  File "/home/ubuntu/hola/hola/test/../hola/hola.py", line 339, in hola
    trunk.fdlayout(iel, False)
  File "/home/ubuntu/hola/hola/test/../hola/graphs.py", line 631, in fdlayout
    useNeighbourStress=useNeighbourStress)
  File "/home/ubuntu/hola/hola/test/../hola/graphs.py", line 657, in setupFDLayout
    alg = adg.ConstrainedFDLayout(rs, es, iel, op)
  File "/home/ubuntu/hola/hola/test/../adaptagrams/adaptagrams.py", line 3226, in __init__
    this = _adaptagrams.new_ConstrainedFDLayout(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_ConstrainedFDLayout'.
  Possible C/C++ prototypes are:
    cola::ConstrainedFDLayout::ConstrainedFDLayout(vpsc::Rectangles const &,std::vector< cola::Edge,std::allocator< cola::Edge > > const &,double const,cola::EdgeLengths const &,cola::TestConvergence *,cola::PreIteration *)
    cola::ConstrainedFDLayout::ConstrainedFDLayout(vpsc::Rectangles const &,std::vector< cola::Edge,std::allocator< cola::Edge > > const &,double const,cola::EdgeLengths const &,cola::TestConvergence *)
    cola::ConstrainedFDLayout::ConstrainedFDLayout(vpsc::Rectangles const &,std::vector< cola::Edge,std::allocator< cola::Edge > > const &,double const,cola::EdgeLengths const &)
    cola::ConstrainedFDLayout::ConstrainedFDLayout(vpsc::Rectangles const &,std::vector< cola::Edge,std::allocator< cola::Edge > > const &,double const)
```

My environment:
Ubuntu 16.04.4
G++ version 5.4.0

**Comment by skieffer** [comment]
Are you using the necessary [experimental fork of Adaptagrams](https://github.com/skieffer/adapaca)? Unfortunately that's still required, and HOLA doesn't yet work with the main Adaptagrams repo.

**Comment by time-river** [comment]
Thanks for your reply. Because I used [mjwybrow/adaptagrams](https://github.com/skieffer/adapaca) instead of [skieffer/adapaca](https://github.com/mjwybrow/adaptagrams/), I made its mistake. It works after I changed depends.
